# Generated by Django 4.1.4 on 2022-12-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0002_alter_progressions_progess_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectentities',
            options={'ordering': ['pk']},
        ),
    ]
