# Generated by Django 4.1.4 on 2023-01-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0003_alter_projectentities_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('notif_type', models.TextField(blank=True, null=True)),
                ('notif_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tache.tasks')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
