# Generated by Django 4.1.4 on 2023-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(max_length=100),
        ),
    ]
