# Generated by Django 4.1.4 on 2023-01-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0005_alter_notification_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tache.phases')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tache.tasks')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
